### PR TITLE
Update recipe, build via pip + pypi, fixate py4j, merge anaconda/master, list scripts, noarch, 2.4.1

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
In case somebody reviewing the commits here ... some commits here do have a detailed commit message ...

**Comment by dbast** [comment]
@conda-forge-admin, please add noarch: python

**Comment by dbast** [comment]
@conda-forge/pyspark Can somebody else please also review this. Thanks

**Comment by parente** [comment]
It looks reasonable to me on the face of it. I have not attempted to pull it locally and test, however.

**Comment by dbast** [comment]
@parente Thanks for taking a look.

Did some testing: 
* Built it locally via `CONFIG=linux_ .azure-pipelines/run_docker_build.sh`
* Compared the content of old to new tar.bz2 via meld -> looks good.
* Installed same build version into 4 freshly created local environments: win + py27, win + py37, osx + py27, osx + py37:
  * all the spark*, pyspark* scripts are available
  * spark-shell and pyspark commands are working
  * importing works and basic DataFrame operation in spark local mode works.

Seems like the conversion from build via setup.py -> pip -> noarch went well.  Good to go from my side.

**Pull request merged**
