### PR TITLE
Spark 2.3.0 is out

### PR DESCRIPTION
**Pull request by ostrokach**

### CODE REVIEW

**Comment by parente** [comment]
Thanks for the PR @ostrokach.

**Comment by parente** [comment]
@conda-forge-admin please rerender

**Comment by parente** [comment]
Build failing with `C:\projects\pyspark-feedstock\recipe: C2122 Found invalid license family "Apache 2.0"` due to conda/conda-verify#38.

**Comment by parente** [comment]
@ostrokach  I think a workaround until the conda-verify PR is worked out is to add a `license_family` key under `about` in the meta.yaml and set it to `Apache` (Ref: https://github.com/conda/conda-build/blob/53aaa0ff24de55d8b44aa9a8a366a549ce0a4636/conda_build/license_family.py#L16 and https://github.com/conda/conda-build/blob/53aaa0ff24de55d8b44aa9a8a366a549ce0a4636/conda_build/license_family.py#L16).

**Comment by dougalsutherland** [comment]
@parente That would work (and you should probably do that anyway), but @isuruf pulled the conda-verify 3 packages for now, so a rebuild should also Just Work. I just hit the re-build button on Appveyor.

**Comment by parente** [comment]
Thanks @dougalsutherland.

**Pull request merged**
