### PR TITLE
Update to PySpark 3.5.3, limit numpy dependency to < 2

### PR DESCRIPTION
**Pull request by codesorcery**
PySpark will only become compatible with NumPy 2 starting with PySpark 4.
Thus, the NumPy dependency has been limited accordingly for PySpark 3.5 in https://github.com/apache/spark/pull/47175
The same should be done here, so that the builds will succeed again.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by codesorcery** [comment]
Build now fails, since only latest version (i.e. `3.5.3`) is available at https://dist.apache.org/repos/dist/release/spark/

**Comment by h-vetinari** [comment]
Hey @codesorcery, thanks for the PR! It seems that @conda-forge/pyspark is not that active anymore, would you like to add yourself as a maintainer here?

**Comment by codesorcery** [comment]
Hi @h-vetinari, I'm not that deep into the build-setup for Conda packages and only use Conda for some side-projects. But if there's no one else maintaining this repository, I could try to do my best to maintain it.

**Comment by h-vetinari** [comment]
Cool! I'll join as well, so you can ask me if you have questions.

**Pull request merged**
