### PR TITLE
REL: 2.1.1

### LINKED ISSUE #2: Upgrade to 2.1.1
Spark 2.1.1 is released including some relevant fixes to the setup.

### PR DESCRIPTION
**Pull request by parente**
Fixes #2

### CODE REVIEW

**Comment by parente** [comment]
Some CI jobs are failing due to SHA256s that differ from what's in the recipe and from each other. The download link is probably load balanced across many servers, but I would at least expect them all to have the same SHA.

**Comment by holdenk** [comment]
That is scary. To unblock I would consider using the "direct" download link from the project page which points to cloudfront mirrors (it's what I use in my travis builds).

I'll cc @srowen who verifies the signatures in all of the Spark releases - I haven't seen this happen either ASF mirroring before so I'm not super sure who to route this too.

**Comment by srowen** [comment]
Hm, yeah there's a problem. I only actually check the sigs of the artifacts I'm interested in, but, the hashes and sigs for the pyspark artifact don't match. (By the way SHA-512 is used here rather than SHA-256 but that's not the problem.)

I don't immediately see any problem with the release script. It doesn't, say, repack the archive or anything. We might need to back and check with Michael on the off chance he recalls something that went wrong with this artifact that could explain it.

But also, yeah, verify that the release script actually produces an artifact that's signed correctly. The other parts all seem to be, just not this.

Feel free to open a JIRA, or I'll do it tomorrow.

**Comment by holdenk** [comment]
So I think this is just a mirror/infra issue most likely - if I manually download the asc file, md5, and shas from the US mirror and verify the signature everything seems to check out.

**Comment by srowen** [comment]
Yeah I just downloaded them all from a US-based machine and all sigs and hashes were fine. I'm in the UK, so it does point to some mirror issue. I downloaded the files again and it was fine, just now in the UK too. Go figure.

**Comment by holdenk** [comment]
Any idea who in infra/how to best notify them?

**Comment by srowen** [comment]
@holdenk I think you just file an INFRA ticket to ask if they can take a look. It might be transient, but hard to say. I couldn't reproduce it in 2 out of 3 cases.

**Pull request merged**
