### PR TITLE
add sbin folder

### PR DESCRIPTION
**Pull request by quasiben**
Occasionally, I and @mrocklin like to use some of the binaries in the `sbin` folder.  Namely, the `start-...` scripts.  This PR adds sbin folder to conda recipe and increments the build number.

### CODE REVIEW

**Comment by parente** [comment]
@quasiben Thanks. It looks like there's a windows failure due to a missing sbin directory. 

I think another way to do this is to include a patch to the pyspark setup.py to include sbin along with bin. That patch can also be a PR against Spark itself.

**Comment by quasiben** [comment]
which path should be go down ?  patch here or spark or both ?  I need the sbin directory for an upcoming tutorial

**Comment by parente** [comment]
Tactically, a patch here, referenced by the recipe/meta.yaml, and the same patch submitted to Spark for a long term fix so we can remove it here eventually.

**Comment by quasiben** [comment]
@parente patch above moves everything in sbin/ to the bin directory

**Comment by quasiben** [comment]
Wait...that won't work.  `start-master.sh` looks for `sbin/spark-config.sh`

**Comment by parente** [comment]
Can the patch not copy from `sbin` to `sbin`?

**Comment by ericdill** [comment]
@quasiben @parente should we close this? Seems inactive for a while now.

**Comment by oulenz** [comment]
FYI, the history server scripts in `sbin` have now been added to the pyspark master branch: https://github.com/apache/spark/pull/23715

**Pull request closed without merging**
